
service: selenium-lambda
# app and org for use with dashboard.serverless.com
app: shapla-app
org: rezahok

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 900


functions:
  hello:
    handler: handler.hello
    layers:
      - ${cf:selenium-layer-dev.SeleniumLayerExport}
      - ${cf:selenium-layer-dev.ChromedriverLayerExport}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3
