
service: selenium-layer
# app and org for use with dashboard.serverless.com
app: shapla-app
org: rezahok

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 900

layers:
  selenium:
    path: selenium
    compatibleRuntimes:
      - "python3.6"
  chromedriver:
    path: chrome_driver
    description: chrome driver layer
    compatibleRuntimes:
      - "python3.6"
resources:
  Outputs:
    SeleniumLayerExport:
        Value:
          Ref: SeleniumLambdaLayer
        Export:
          Name: SeleniumLambdaLayer
    ChromedriverLayerExport:
      Value:
        Ref: ChromedriverLambdaLayer
      Export:
        Name: ChromedriverLambdaLayer